// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0--rc1
// source: proto/events/execution_job.proto

package eventspb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type JobType int32

const (
	JobType_RUN    JobType = 0
	JobType_CANCEL JobType = 1
)

// Enum value maps for JobType.
var (
	JobType_name = map[int32]string{
		0: "RUN",
		1: "CANCEL",
	}
	JobType_value = map[string]int32{
		"RUN":    0,
		"CANCEL": 1,
	}
)

func (x JobType) Enum() *JobType {
	p := new(JobType)
	*p = x
	return p
}

func (x JobType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (JobType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_events_execution_job_proto_enumTypes[0].Descriptor()
}

func (JobType) Type() protoreflect.EnumType {
	return &file_proto_events_execution_job_proto_enumTypes[0]
}

func (x JobType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use JobType.Descriptor instead.
func (JobType) EnumDescriptor() ([]byte, []int) {
	return file_proto_events_execution_job_proto_rawDescGZIP(), []int{0}
}

type ExecutionJob struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ExecutionId     string                 `protobuf:"bytes,1,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"`
	UserId          string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	FunctionId      string                 `protobuf:"bytes,3,opt,name=function_id,json=functionId,proto3" json:"function_id,omitempty"`
	VersionId       string                 `protobuf:"bytes,4,opt,name=version_id,json=versionId,proto3" json:"version_id,omitempty"`
	CodeStoragePath string                 `protobuf:"bytes,5,opt,name=code_storage_path,json=codeStoragePath,proto3" json:"code_storage_path,omitempty"`
	Runtime         string                 `protobuf:"bytes,6,opt,name=runtime,proto3" json:"runtime,omitempty"`
	InputPayload    string                 `protobuf:"bytes,7,opt,name=input_payload,json=inputPayload,proto3" json:"input_payload,omitempty"`
	TimeoutSeconds  int32                  `protobuf:"varint,8,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`
	JobType         JobType                `protobuf:"varint,9,opt,name=job_type,json=jobType,proto3,enum=veltrix.events.JobType" json:"job_type,omitempty"`
	RetryCount      int32                  `protobuf:"varint,10,opt,name=retry_count,json=retryCount,proto3" json:"retry_count,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ExecutionJob) Reset() {
	*x = ExecutionJob{}
	mi := &file_proto_events_execution_job_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecutionJob) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecutionJob) ProtoMessage() {}

func (x *ExecutionJob) ProtoReflect() protoreflect.Message {
	mi := &file_proto_events_execution_job_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecutionJob.ProtoReflect.Descriptor instead.
func (*ExecutionJob) Descriptor() ([]byte, []int) {
	return file_proto_events_execution_job_proto_rawDescGZIP(), []int{0}
}

func (x *ExecutionJob) GetExecutionId() string {
	if x != nil {
		return x.ExecutionId
	}
	return ""
}

func (x *ExecutionJob) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ExecutionJob) GetFunctionId() string {
	if x != nil {
		return x.FunctionId
	}
	return ""
}

func (x *ExecutionJob) GetVersionId() string {
	if x != nil {
		return x.VersionId
	}
	return ""
}

func (x *ExecutionJob) GetCodeStoragePath() string {
	if x != nil {
		return x.CodeStoragePath
	}
	return ""
}

func (x *ExecutionJob) GetRuntime() string {
	if x != nil {
		return x.Runtime
	}
	return ""
}

func (x *ExecutionJob) GetInputPayload() string {
	if x != nil {
		return x.InputPayload
	}
	return ""
}

func (x *ExecutionJob) GetTimeoutSeconds() int32 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

func (x *ExecutionJob) GetJobType() JobType {
	if x != nil {
		return x.JobType
	}
	return JobType_RUN
}

func (x *ExecutionJob) GetRetryCount() int32 {
	if x != nil {
		return x.RetryCount
	}
	return 0
}

var File_proto_events_execution_job_proto protoreflect.FileDescriptor

const file_proto_events_execution_job_proto_rawDesc = "" +
	"\n" +
	" proto/events/execution_job.proto\x12\x0eveltrix.events\"\xf3\x02\n" +
	"\fExecutionJob\x12!\n" +
	"\fexecution_id\x18\x01 \x01(\tR\vexecutionId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1f\n" +
	"\vfunction_id\x18\x03 \x01(\tR\n" +
	"functionId\x12\x1d\n" +
	"\n" +
	"version_id\x18\x04 \x01(\tR\tversionId\x12*\n" +
	"\x11code_storage_path\x18\x05 \x01(\tR\x0fcodeStoragePath\x12\x18\n" +
	"\aruntime\x18\x06 \x01(\tR\aruntime\x12#\n" +
	"\rinput_payload\x18\a \x01(\tR\finputPayload\x12'\n" +
	"\x0ftimeout_seconds\x18\b \x01(\x05R\x0etimeoutSeconds\x122\n" +
	"\bjob_type\x18\t \x01(\x0e2\x17.veltrix.events.JobTypeR\ajobType\x12\x1f\n" +
	"\vretry_count\x18\n" +
	" \x01(\x05R\n" +
	"retryCount*\x1e\n" +
	"\aJobType\x12\a\n" +
	"\x03RUN\x10\x00\x12\n" +
	"\n" +
	"\x06CANCEL\x10\x01B\x18Z\x16veltrix/proto/eventspbb\x06proto3"

var (
	file_proto_events_execution_job_proto_rawDescOnce sync.Once
	file_proto_events_execution_job_proto_rawDescData []byte
)

func file_proto_events_execution_job_proto_rawDescGZIP() []byte {
	file_proto_events_execution_job_proto_rawDescOnce.Do(func() {
		file_proto_events_execution_job_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_events_execution_job_proto_rawDesc), len(file_proto_events_execution_job_proto_rawDesc)))
	})
	return file_proto_events_execution_job_proto_rawDescData
}

var file_proto_events_execution_job_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_events_execution_job_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_events_execution_job_proto_goTypes = []any{
	(JobType)(0),         // 0: veltrix.events.JobType
	(*ExecutionJob)(nil), // 1: veltrix.events.ExecutionJob
}
var file_proto_events_execution_job_proto_depIdxs = []int32{
	0, // 0: veltrix.events.ExecutionJob.job_type:type_name -> veltrix.events.JobType
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_events_execution_job_proto_init() }
func file_proto_events_execution_job_proto_init() {
	if File_proto_events_execution_job_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_events_execution_job_proto_rawDesc), len(file_proto_events_execution_job_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_events_execution_job_proto_goTypes,
		DependencyIndexes: file_proto_events_execution_job_proto_depIdxs,
		EnumInfos:         file_proto_events_execution_job_proto_enumTypes,
		MessageInfos:      file_proto_events_execution_job_proto_msgTypes,
	}.Build()
	File_proto_events_execution_job_proto = out.File
	file_proto_events_execution_job_proto_goTypes = nil
	file_proto_events_execution_job_proto_depIdxs = nil
}
