// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0--rc1
// source: proto/events/execution_event.proto

package eventspb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ExecutionEventType int32

const (
	ExecutionEventType_EXECUTION_STARTED   ExecutionEventType = 0
	ExecutionEventType_EXECUTION_COMPLETED ExecutionEventType = 1
	ExecutionEventType_EXECUTION_FAILED    ExecutionEventType = 2
	ExecutionEventType_EXECUTION_CANCELLED ExecutionEventType = 3
)

// Enum value maps for ExecutionEventType.
var (
	ExecutionEventType_name = map[int32]string{
		0: "EXECUTION_STARTED",
		1: "EXECUTION_COMPLETED",
		2: "EXECUTION_FAILED",
		3: "EXECUTION_CANCELLED",
	}
	ExecutionEventType_value = map[string]int32{
		"EXECUTION_STARTED":   0,
		"EXECUTION_COMPLETED": 1,
		"EXECUTION_FAILED":    2,
		"EXECUTION_CANCELLED": 3,
	}
)

func (x ExecutionEventType) Enum() *ExecutionEventType {
	p := new(ExecutionEventType)
	*p = x
	return p
}

func (x ExecutionEventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ExecutionEventType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_events_execution_event_proto_enumTypes[0].Descriptor()
}

func (ExecutionEventType) Type() protoreflect.EnumType {
	return &file_proto_events_execution_event_proto_enumTypes[0]
}

func (x ExecutionEventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ExecutionEventType.Descriptor instead.
func (ExecutionEventType) EnumDescriptor() ([]byte, []int) {
	return file_proto_events_execution_event_proto_rawDescGZIP(), []int{0}
}

type ExecutionStatus int32

const (
	ExecutionStatus_EXECUTION_STATUS_UNSPECIFIED ExecutionStatus = 0
	ExecutionStatus_EXECUTION_STATUS_RETRY       ExecutionStatus = 1
)

// Enum value maps for ExecutionStatus.
var (
	ExecutionStatus_name = map[int32]string{
		0: "EXECUTION_STATUS_UNSPECIFIED",
		1: "EXECUTION_STATUS_RETRY",
	}
	ExecutionStatus_value = map[string]int32{
		"EXECUTION_STATUS_UNSPECIFIED": 0,
		"EXECUTION_STATUS_RETRY":       1,
	}
)

func (x ExecutionStatus) Enum() *ExecutionStatus {
	p := new(ExecutionStatus)
	*p = x
	return p
}

func (x ExecutionStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ExecutionStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_events_execution_event_proto_enumTypes[1].Descriptor()
}

func (ExecutionStatus) Type() protoreflect.EnumType {
	return &file_proto_events_execution_event_proto_enumTypes[1]
}

func (x ExecutionStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ExecutionStatus.Descriptor instead.
func (ExecutionStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_events_execution_event_proto_rawDescGZIP(), []int{1}
}

type ExecutionEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExecutionId   string                 `protobuf:"bytes,1,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"`
	WorkerId      string                 `protobuf:"bytes,2,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	EventType     ExecutionEventType     `protobuf:"varint,3,opt,name=event_type,json=eventType,proto3,enum=veltrix.events.ExecutionEventType" json:"event_type,omitempty"`
	Timestamp     string                 `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,5,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	Status        ExecutionStatus        `protobuf:"varint,6,opt,name=status,proto3,enum=veltrix.events.ExecutionStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecutionEvent) Reset() {
	*x = ExecutionEvent{}
	mi := &file_proto_events_execution_event_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecutionEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecutionEvent) ProtoMessage() {}

func (x *ExecutionEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_events_execution_event_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecutionEvent.ProtoReflect.Descriptor instead.
func (*ExecutionEvent) Descriptor() ([]byte, []int) {
	return file_proto_events_execution_event_proto_rawDescGZIP(), []int{0}
}

func (x *ExecutionEvent) GetExecutionId() string {
	if x != nil {
		return x.ExecutionId
	}
	return ""
}

func (x *ExecutionEvent) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *ExecutionEvent) GetEventType() ExecutionEventType {
	if x != nil {
		return x.EventType
	}
	return ExecutionEventType_EXECUTION_STARTED
}

func (x *ExecutionEvent) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *ExecutionEvent) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *ExecutionEvent) GetStatus() ExecutionStatus {
	if x != nil {
		return x.Status
	}
	return ExecutionStatus_EXECUTION_STATUS_UNSPECIFIED
}

var File_proto_events_execution_event_proto protoreflect.FileDescriptor

const file_proto_events_execution_event_proto_rawDesc = "" +
	"\n" +
	"\"proto/events/execution_event.proto\x12\x0eveltrix.events\"\x8f\x02\n" +
	"\x0eExecutionEvent\x12!\n" +
	"\fexecution_id\x18\x01 \x01(\tR\vexecutionId\x12\x1b\n" +
	"\tworker_id\x18\x02 \x01(\tR\bworkerId\x12A\n" +
	"\n" +
	"event_type\x18\x03 \x01(\x0e2\".veltrix.events.ExecutionEventTypeR\teventType\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\tR\ttimestamp\x12#\n" +
	"\rerror_message\x18\x05 \x01(\tR\ferrorMessage\x127\n" +
	"\x06status\x18\x06 \x01(\x0e2\x1f.veltrix.events.ExecutionStatusR\x06status*s\n" +
	"\x12ExecutionEventType\x12\x15\n" +
	"\x11EXECUTION_STARTED\x10\x00\x12\x17\n" +
	"\x13EXECUTION_COMPLETED\x10\x01\x12\x14\n" +
	"\x10EXECUTION_FAILED\x10\x02\x12\x17\n" +
	"\x13EXECUTION_CANCELLED\x10\x03*O\n" +
	"\x0fExecutionStatus\x12 \n" +
	"\x1cEXECUTION_STATUS_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16EXECUTION_STATUS_RETRY\x10\x01B\x18Z\x16veltrix/proto/eventspbb\x06proto3"

var (
	file_proto_events_execution_event_proto_rawDescOnce sync.Once
	file_proto_events_execution_event_proto_rawDescData []byte
)

func file_proto_events_execution_event_proto_rawDescGZIP() []byte {
	file_proto_events_execution_event_proto_rawDescOnce.Do(func() {
		file_proto_events_execution_event_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_events_execution_event_proto_rawDesc), len(file_proto_events_execution_event_proto_rawDesc)))
	})
	return file_proto_events_execution_event_proto_rawDescData
}

var file_proto_events_execution_event_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_events_execution_event_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_events_execution_event_proto_goTypes = []any{
	(ExecutionEventType)(0), // 0: veltrix.events.ExecutionEventType
	(ExecutionStatus)(0),    // 1: veltrix.events.ExecutionStatus
	(*ExecutionEvent)(nil),  // 2: veltrix.events.ExecutionEvent
}
var file_proto_events_execution_event_proto_depIdxs = []int32{
	0, // 0: veltrix.events.ExecutionEvent.event_type:type_name -> veltrix.events.ExecutionEventType
	1, // 1: veltrix.events.ExecutionEvent.status:type_name -> veltrix.events.ExecutionStatus
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_events_execution_event_proto_init() }
func file_proto_events_execution_event_proto_init() {
	if File_proto_events_execution_event_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_events_execution_event_proto_rawDesc), len(file_proto_events_execution_event_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_events_execution_event_proto_goTypes,
		DependencyIndexes: file_proto_events_execution_event_proto_depIdxs,
		EnumInfos:         file_proto_events_execution_event_proto_enumTypes,
		MessageInfos:      file_proto_events_execution_event_proto_msgTypes,
	}.Build()
	File_proto_events_execution_event_proto = out.File
	file_proto_events_execution_event_proto_goTypes = nil
	file_proto_events_execution_event_proto_depIdxs = nil
}
